### ISSUE TITLE
Generate CTF Tomoseries ?

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-aretomo#56] opened 2024-01-18 11:37 UTC
New aretomo generates cistem files..... shouldn't we register a set of CTFTomoseries as output or aretomo?

**Comment by JorMaister** [comment] 2024-01-19 08:24
Yes, we should. Indeed, The problem found here is that the CTF generated is of the size of the TS without considering the excluded tilt images (if there are any). To be coherent with the data model (binary file size does not change, storing the excluded views as an Enable field in the metadata), it should be necessary to add the missing CTF lines in the required position (based on the exclusion indices) so that the sizes match. It'd be just the same as when tilt images are excluded for the TS alignment, adding the corresponding registries with the rotation angle and shifts equal to zero.

@azazellochg, do you want to take this task? If you're overloaded or something, I can do it myself.

**Comment by azazellochg** [comment] 2024-01-19 10:22
the problem is imho is that every few versions the output format of this program changes. I don't want this task, @JorMaister please go ahead, I'm happy to review more PRs :)

**Comment by JorMaister** [comment] 2024-01-19 10:31
Ok, I'll assign it to myself, @azazellochg. Let's see if they finally keep the format more stable.

**Closed** 2024-02-17 13:54 UTC
